source 'http://rubygems.org'

gem 'rails', '3.0.6'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem "heritage", :path => '../'

group :test do
	gem 'rspec-rails'
	gem 'factory_girl_rails'
	gem 'autotest'
	gem 'autotest-fsevent'
	gem 'autotest-growl'
	gem "heritage", :path => '../'
end
